# Generated by Django 3.0.3 on 2020-04-21 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pluton.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegisterations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('emailid', models.CharField(max_length=200, validators=[pluton.models.validate_mail])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('college_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[pluton.models.validate_phone])),
                ('event', models.CharField(choices=[('Culturals', 'CULTURALS'), ('Sci_tech', 'SCIENCE & TECHNOLOGY'), ('Sports', 'SPORTS'), ('ArtLit', 'ART & LITERATURE')], default=None, max_length=30, null=True)),
                ('members', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('project_idea', models.TextField()),
                ('tshirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
